name: mojtam3
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.19+21

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: any
  dotted_border: ^1.0.4
  pin_input_text_field: ^1.0.1
  intl_translation: ^0.17.1
  image_cropper: ^1.1.1
  image_picker: ^0.6.1
  dio: ^3.0.3
  http: ^0.12.0+2
  rflutter_alert: ^1.0.3 # AlertDialog
  email_validator: ^1.0.0
  toast: ^0.1.5
  flutter_date_picker: ^0.1.8 
  flutter_tags: ^0.4.5
  cached_network_image: any
  progressive_image: ^1.0.0
  photo_view: ^0.9.0
  firebase_storage: any
  cloud_firestore: any
  # connectivity: ^0.4.6+1
  webview_flutter: any
  firebase_messaging: any
  video_player: any
  firebase_core: any
  multi_image_picker: any
  carousel_slider: ^1.3.1
  flutter_slidable: "^0.5.4"
  flutter_local_notifications: any
  path_provider: any
  awesome_dialog: any
  flutter_launcher_icons: "^0.7.3"
  audio_recorder: any
  # simple_permissions: '^0.1.9'
  uuid: '>=1.0.0'
  path: '>=1.5.1'
  audioplayers: any
  permission_handler: '^4.2.0+hotfix.3'
  rxdart: any
  # # multi_type_list_view: ^0.1.0
  # # rxdart: ^0.23.1
  # flutter_swiper: ^1.1.6
  # date_format: ^1.0.8
  # # image_picker: ^0.6.2+3
  # # path_provider: ^1.5.1
  # flutter_staggered_animations: ^0.1.2
  # # photo_view: ^0.9.0
  provider: any
  image_downloader: ^0.19.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  # multi_type_list_view:
  #http: ^0.12.0+2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logomogtama3.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: black
      fonts:
        - asset: fonts/bein-ar-black.ttf
    - family: thin
      fonts:
        - asset: fonts/bein-ar-normal.ttf


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
    - assets/background.png
    - assets/logo.png
    - assets/splash.png
    - assets/Rectangle1.png
    - assets/Rectangle2.png
    - assets/Rectangle3.png
    - assets/soud.jpg
    - assets/recta.png
    - assets/cccc.png
    - assets/location.png
    - assets/gallery.jpg
    - assets/camera.jpg

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
